Updates description of yogs
spacestation13/website pull request #123
Opened 2024-07-26 19:48 UTC by ToasterBiome

it was simply cringe

2024-08-14 03:34 UTC, ToasterBiome commented
ill fix it eventually

2024-08-16 14:58 UTC, Wirewraith requested changes

2024-08-16 14:58 UTC, Wirewraith commented on content/servers.json5
> +				'Yogstation was founded in 2011 after the previous host asked the Yogscast for their blessing to open an SS13 server in their name. The Yogscast allowed this, and even played on the server a hand
```suggestion
				'Yogstation was founded in 2011 after the previous host asked the Yogscast for their blessing to open an SS13 server in their name. The Yogscast allowed this, and even played on the server a handful of times during its formative years. As a fork of /tg/station, Yogstation features it\'s own unique spin on the TG formula. The server is ran by a council of elected staff, and boasts many mentors and developers making the game better day by day. Rounds fluctuate between action packed team-based antagonists that other servers lack and slower, more peaceful solo antagonist rounds. Game Masters run interesting events, and there is always a new feature in the works. 99% Lag Free.',
```

2024-08-22 16:56 UTC, ZeWaka approved these changes

2025-03-01 17:37 UTC, closed without merging